Median
lupiz-0/exercises-qt pull request #22
Opened 2020-10-21 13:12 UTC by lupiz-0

Permettere l'input di un certo numero di valori, restituire la mediana.

2020-10-21 13:56 UTC, MuAlphaOmegaEpsilon commented on median/main.cpp
> +    for(ulong i = 0; i < values.size(); i++){
Usiamo `size_t` piuttosto che `ulong` per il tipo. Da dove l'hai preso a proposito ulong?

2020-10-21 14:03 UTC, MuAlphaOmegaEpsilon reviewed
In generale ottimo!
Anche qui non mi fa impazzire l'input lato utente, ma al momento non gli do molta importanza. :+1:

2020-10-21 14:38 UTC, lucaotta requested changes

2020-10-21 14:38 UTC, lucaotta commented on median/main.cpp
> +    }
Questo è un bel candidato per `std::for_each()`, ma se non lo vuoi scomodare almeno usiamo un range_for:
```suggestion
    for(const auto &v : values){
        cout << v << " ";
    }
```

2020-10-22 07:16 UTC, lupiz-0 commented on median/main.cpp
> +    for(ulong i = 0; i < values.size(); i++){
Avevo messo int inizialmente, ma qt cretor suggeriva di usare un unsigned long

2020-10-22 07:23 UTC, merged