Day2 es2 (recipes)
lupiz-0/exercises-qt pull request #5
Opened 2020-09-17 15:26 UTC by lupiz-0

2020-09-18 12:58 UTC, lucaotta requested changes

2020-09-18 12:58 UTC, lucaotta commented on day2/es2/Recipe.qml
> +Item {
Bene, hai usato un `Item` invece di un `Rectangle`!
Tutti i componenti che non hanno una rappresentazione grafica possono però essere dei `QtObject`.

2020-09-18 12:58 UTC, lucaotta commented on day2/es2/RecipePage.qml
> +    onClicked: back()
:+1:

2020-09-18 12:58 UTC, lucaotta commented on day2/es2/es2.qml
> +                width: mainWindow.width
Questo mi fa strano...un delegate in una lista che non è largo quanto la lista ma quanto la mainWindow... :open_mouth: 
Io metterei qualcosa del tipo `ListView.view.width` (o in alternativa dai un `id` alla ListView)

2020-09-18 13:50 UTC, lupiz-0 commented on day2/es2/es2.qml
> +                width: mainWindow.width
si funziona con `ListView.view.width`

2020-09-21 07:30 UTC, MuAlphaOmegaEpsilon commented
Non noto niente di particolare da commentare lato codice: ottimo lavoro! :+1: 

Forse l'unica cosa che non mi convince è il naming dei file `Recipe.qml` e `RecipeSlot.qml`.

`Recipe.qml` contiene solo un enum `Difficulty`, pertanto credo sarebbe stato più appropriato chiamarlo `RecipeDifficulty.qml`.

`RecipePage.qml` mi sembra un nome adeguato, trattandosi di una pagina dedicata con le descrizioni.

`RecipeSlot.qml` invece non mi convince in parte per l'uso del termine `slot`, che come vedrai più avanti in Qt viene usato spesso in C++ per l'implementazione del meccanismo dei segnali (SIGNAL->SLOT), in parte perchè non mi è immediatamente chiaro cosa dovrebbe essere un `RecipeSlot`.
Fosse dipeso da me, forse avrei optato per qualcosa del tipo `RecipeEntry`, a cui probabilmente avrei aggiunto il suffisso `Delegate` per rendere esplicito che fosse un componente pensato per essere usato come rappresentazione grafica in una lista: il file avrebbe finito per chiamarsi `RecipeEntryDelegate.qml`. 

Non dico che siano necessariamente la scelta migliore, ma credo siano migliorie.
In ogni caso non serve modificarli adesso, è solo una considerazione per i prossimi esercizi! :)

2020-09-21 07:34 UTC, merged